[package]
name = "vicki"
version = "0.1.0"
authors = ["Tomasz Stachowiak <h3@h3.gd>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.31"
ash-window = "0.5"
anyhow = "1.0"
hassle-rs = "0.4"
log = "0.4"
fern = { version = "0.6", features = ["colored"] }
chrono = "0.4"
raw-window-handle = "0.3"
spirv-reflect = { git = "https://github.com/h3r2tic/spirv-reflect-rs.git", rev = "a51ba47" }    # pure Rust version, SPIR-V 1.3+ fixes, ray-tracing
thiserror = "1.0"
vk-mem = { git = "https://github.com/cheako/vk-mem-rs.git", rev = "4a5f613" }   # Ray tracing and VK 1.2 support
vk-sync = { git = "https://github.com/zedrian/vk-sync-rs.git", rev = "e28c05d" }
winit = "0.22"
