[package]
name = "vicki"
version = "0.1.0"
authors = ["Tomasz Stachowiak <h3@h3.gd>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
arrayvec = "0.5"
ash-imgui = { path = "ash-imgui" }
blue-noise-sampler = "0.1"
byte-slice-cast = "0.3"
byteorder = "1.4"
chrono = "0.4"
#derive_builder = { git = "https://github.com/colin-kiegel/rust-derive-builder.git", rev = "44f629c", features = ["logging"] }   # dyn Error instead of String
derive_builder = { version = "0.9", default-features = false }
failure = "0.1.8"   # for shader-prepper: TODO: NUKE
fern = { version = "0.6", features = ["colored"] }
futures = "0.3"
glam = "0.12"
gltf = "0.15"
hassle-rs = "0.4"
hotwatch = "0.4"
image = { version = "0.23.13", default-features = false, features = ["gif", "jpeg", "ico", "png", "pnm", "tga", "tiff", "webp", "bmp", "hdr", "dxt"] }
imgui = { git = "https://github.com/Gekkio/imgui-rs.git", rev = "ffff82d" }
imgui-winit-support = { git = "https://github.com/Gekkio/imgui-rs.git", rev = "ffff82d", features = ["winit-19"] }
lazy_static = "1.4"
log = "0.4"
memmap2 = "0.2"
# once_cell = "1.4"
parking_lot = "0.11"
raw-window-handle = "0.3"
relative-path = "1.3"
smol = "1.2.5"
structopt = "0.3"
thiserror = "1.0"
turbosloth = "0.2.0"
slingshot = { path = "crates/slingshot" }
# winit = "0.21"  # 0.22 panics in NSight with this error: https://github.com/rust-windowing/winit/issues/1585
winit = "=0.19.5"

async-channel = "1.4.2"
async-executor = "1.1.0"
easy-parallel = "3.1.0"

[patch.crates-io]
turbosloth = { path = "../turbosloth" }

# Official ray-tracing extensions
ash = { git = "https://github.com/MaikKlein/ash.git", rev = "7fa182cc4330da8da98a7c023049162a4979d0bf" }
rspirv = { git = "https://github.com/gfx-rs/rspirv.git", rev = "dae552c" }
spirv_headers = { git = "https://github.com/gfx-rs/rspirv.git", rev = "dae552c" }

[profile.release]
debug = true
incremental = true
lto = false
