[workspace]
members = [
    "bin/bake",

    "crates/kajiya-asset",
    "crates/kajiya-backend",
    "crates/kajiya-rg",
    "crates/kajiya",

    "crates/ash-imgui",
]

[patch.crates-io]
# Official ray-tracing extensions
rspirv = { git = "https://github.com/gfx-rs/rspirv.git", rev = "dae552c" }
spirv_headers = { git = "https://github.com/gfx-rs/rspirv.git", rev = "dae552c" }
