[package]
name = "kajiya"
version = "0.1.0"
authors = ["Tomasz Stachowiak <h3@h3.gd>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash-imgui = { path = "crates/ash-imgui" }
kajiya-backend = { path = "crates/kajiya-backend" }
kajiya-rg = { path = "crates/kajiya-rg" }

anyhow = "1.0"
arrayvec = "0.5"
blue-noise-sampler = "0.1"
byte-slice-cast = "0.3"
byteorder = "1.4"
chrono = "0.4"
derive_builder = { version = "0.9", default-features = false }
failure = "0.1.8"   # for shader-prepper: TODO: NUKE
fern = { version = "0.6", features = ["colored"] }
futures = "0.3"
glam = "0.12"
gltf = { git = "https://github.com/gltf-rs/gltf.git", rev = "4298aac", features = ["KHR_texture_transform"] } # texture transform
hassle-rs = "0.4"
hotwatch = "0.4"
image = { version = "0.23.13", default-features = false, features = ["gif", "jpeg", "ico", "png", "pnm", "tga", "tiff", "webp", "bmp", "hdr", "dxt"] }
imgui = "0.7"
imgui-winit-support = "0.7"
lazy_static = "1.4"
log = "0.4"
memmap2 = "0.2"
parking_lot = "0.11"
raw-window-handle = "0.3"
relative-path = "1.3"
ron = "0.6.2"
serde = { version = "1.0", features = ["derive"] }
smol = "1.2.5"
structopt = "0.3"
thiserror = "1.0"
turbosloth = { git = "https://github.com/h3r2tic/turbosloth.git", rev = "92030af" }
# winit = "0.21"  # 0.22 panics in NSight with this error: https://github.com/rust-windowing/winit/issues/1585
# winit = "=0.19.5"
winit = "0.24"

async-channel = "1.4.2"
async-executor = "1.1.0"
easy-parallel = "3.1.0"

[patch.crates-io]
# Official ray-tracing extensions
rspirv = { git = "https://github.com/gfx-rs/rspirv.git", rev = "dae552c" }
spirv_headers = { git = "https://github.com/gfx-rs/rspirv.git", rev = "dae552c" }

[profile.release]
debug = true
incremental = true
lto = false
