[workspace]
members = [
    "crates/bin/bake",
    "crates/bin/view",

    "crates/lib/kajiya-asset",
    "crates/lib/kajiya-backend",
    "crates/lib/kajiya-imgui",
    "crates/lib/kajiya-rg",
    "crates/lib/kajiya-simple",
    "crates/lib/kajiya",

    "crates/lib/ash-imgui",
]

[patch.crates-io]
# Official ray-tracing extensions
rspirv = { git = "https://github.com/gfx-rs/rspirv.git", rev = "dae552c" }
spirv_headers = { git = "https://github.com/gfx-rs/rspirv.git", rev = "dae552c" }
